//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Add_To_Cart_v1.demo {
    
    
    public partial class WebForm1 {
        
        /// <summary>
        /// LVProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView LVProducts;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Add_To_Cart_v1.demo.AddToCartDemo Master {
            get {
                return ((Add_To_Cart_v1.demo.AddToCartDemo)(base.Master));
            }
        }
    }
}
